// Generated by: setup
// TypeWriter: slice
// Directive: +test on Other

package main

import "errors"

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

// OtherSlice is a slice of type Other. Use it where you would use []Other.
type OtherSlice []Other

// Max returns the maximum value of OtherSlice. In the case of multiple items being equally maximal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#Max
func (rcv OtherSlice) Max() (result Other, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Max of an empty slice")
		return
	}
	result = rcv[0]
	for _, v := range rcv {
		if v > result {
			result = v
		}
	}
	return
}

// Min returns the minimum value of OtherSlice. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#Min
func (rcv OtherSlice) Min() (result Other, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	result = rcv[0]
	for _, v := range rcv {
		if v < result {
			result = v
		}
	}
	return
}

// Average sums OtherSlice over all elements and divides by len(OtherSlice). See: http://clipperhouse.github.io/gen/#Average
func (rcv OtherSlice) Average() (Other, error) {
	var result Other

	l := len(rcv)
	if l == 0 {
		return result, errors.New("cannot determine Average of zero-length OtherSlice")
	}
	for _, v := range rcv {
		result += v
	}
	result = result / Other(l)
	return result, nil
}

// Sum sums Other elements in OtherSlice. See: http://clipperhouse.github.io/gen/#Sum
func (rcv OtherSlice) Sum() (result Other) {
	for _, v := range rcv {
		result += v
	}
	return
}

// Sort returns a new ordered OtherSlice. See: http://clipperhouse.github.io/gen/#Sort
func (rcv OtherSlice) Sort() OtherSlice {
	less := func(a, b Other) bool {
		return a < b
	}
	return rcv.sortBy(less)
}

// IsSorted reports whether OtherSlice is sorted. See: http://clipperhouse.github.io/gen/#Sort
func (rcv OtherSlice) IsSorted() bool {
	less := func(a, b Other) bool {
		return a < b
	}
	return rcv.isSortedBy(less)
}

// SortDesc returns a new reverse-ordered OtherSlice. See: http://clipperhouse.github.io/gen/#Sort
func (rcv OtherSlice) SortDesc() OtherSlice {
	greater := func(a, b Other) bool {
		return b < a
	}
	return rcv.sortBy(greater)
}

// IsSortedDesc reports whether OtherSlice is reverse-sorted. See: http://clipperhouse.github.io/gen/#Sort
func (rcv OtherSlice) IsSortedDesc() bool {
	greater := func(a, b Other) bool {
		return b < a
	}
	return rcv.isSortedBy(greater)
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func (rcv OtherSlice) sortBy(less func(Other, Other) bool) OtherSlice {
	result := make(OtherSlice, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortOtherSlice(result, less, 0, n, maxDepth)
	return result
}

func (rcv OtherSlice) isSortedBy(less func(Other, Other) bool) bool {
	n := len(rcv)
	for i := n - 1; i > 0; i-- {
		if less(rcv[i], rcv[i-1]) {
			return false
		}
	}
	return true
}

func swapOtherSlice(rcv OtherSlice, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortOtherSlice(rcv OtherSlice, less func(Other, Other) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapOtherSlice(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownOtherSlice(rcv OtherSlice, less func(Other, Other) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapOtherSlice(rcv, first+root, first+child)
		root = child
	}
}

func heapSortOtherSlice(rcv OtherSlice, less func(Other, Other) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownOtherSlice(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapOtherSlice(rcv, first, first+i)
		siftDownOtherSlice(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeOtherSlice(rcv OtherSlice, less func(Other, Other) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapOtherSlice(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapOtherSlice(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapOtherSlice(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeOtherSlice(rcv OtherSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		swapOtherSlice(rcv, a+i, b+i)
	}
}

func doPivotOtherSlice(rcv OtherSlice, less func(Other, Other) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeOtherSlice(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeOtherSlice(rcv, less, m, m-s, m+s)
		medianOfThreeOtherSlice(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeOtherSlice(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapOtherSlice(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapOtherSlice(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapOtherSlice(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeOtherSlice(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeOtherSlice(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortOtherSlice(rcv OtherSlice, less func(Other, Other) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortOtherSlice(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotOtherSlice(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortOtherSlice(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortOtherSlice(rcv, mhi, b)
		} else {
			quickSortOtherSlice(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortOtherSlice(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortOtherSlice(rcv, less, a, b)
	}
}
